# Generated by Django 3.2.16 on 2022-11-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ceo_nickname', models.CharField(max_length=24, unique=True)),
                ('ceo_name', models.CharField(max_length=24)),
                ('ceo_email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'CEO_User',
            },
        ),
    ]
