# Generated by Django 3.2.16 on 2022-11-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ceo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CEO',
        ),
    ]
